name: example
description: Charts-Flutter Demo
environment:
  sdk: ">=3.4.3"
  flutter: ">=3.19.3"

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ^0.19.0
flutter:
  uses-material-design: true
